baseURL = 'https://www.hqdosarquitectos.com/'
languageCode = 'en-us'
title = 'HQ2 Arquitectos.'
theme = 'tella'
author = "cerberusguardnet"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
enableRobotsTXT = true

# If you're using Google Analytics, you can enable this feature.
#googleAnalytics = "UA-12345678-1"

# Disqus Comment System
#disqusShortname = ""

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.asciidocExt]
    backend = 'html5'
    extensions = []
    failureLevel = 'fatal'
    noHeaderOrFooter = true
    preserveTOC = false
    safeMode = 'unsafe'
    sectionNumbers = false
    trace = false
    verbose = false
    workingFolderCurrent = false
    [markup.asciidocExt.attributes]

[params]

  showBlog = false
  mainSections = ['products']
  googleFonts = true
  ignoreLogs = ['warning-goldmark-raw-html']

  [params.logo]
    main = "img/logo/hqdos4-284x108.png"
    alt = "HQ2 Arquitectos logo"

    # The size parameter is the class name of tailwindcss
    # https://tailwindcss.com/
    size = "h-14"

  [params.icon]
    #If you want to use FontAwesome, set this parameter to true.
    fontawesome = true

  [params.homepage_meta_tags]
    meta_description = "Soluciones Autom치ticas que Impulsan tu Proyecto: Innovaci칩n en Puertas, Andenes y Accesos para Espacios Industriales y Residenciales."
    meta_og_title = "hqdosarquitectos"
    meta_og_type = "hqdosarquitectos"
    meta_og_url = "https://hqdosarquitectos.com"
    meta_og_image = "https://hqdosarquitectos.com/img/logo/hqdos4-284x108.png"
    meta_og_description = "Soluciones Autom치ticas que Impulsan tu Proyecto: Innovaci칩n en Puertas, Andenes y Accesos para Espacios Industriales y Residenciales."

[menu]

  [[menu.main]]
    identifier = "products"
    name = "Productos"
    url = "/products/"
    weight = 1

  [[menu.main]]
    identifier = "services"
    name = "Servicios"
    url = "/services/"
    weight = 2

  [[menu.main]]
    identifier = "contact"
    name = "Contactanos"
    url = "/contact/"
    weight = 3
