baseURL = 'https://www.hqdosarquitectos.com/'
languageCode = 'en-us'
title = 'HQ2 Arquitectos.'
theme = 'tella'
author = "cerberusguardnet"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
enableRobotsTXT = true

# If you're using Google Analytics, you can enable this feature.
#googleAnalytics = "UA-12345678-1"

# Disqus Comment System
#disqusShortname = ""

[params]

  showBlog = false
  mainSections = ['products']
  googleFonts = true

  [params.logo]
    main = "img/logo/hqdos4-284x108.png"
    alt = "HQ2 Arquitectos logo"

    # The size parameter is the class name of tailwindcss
    # https://tailwindcss.com/
    size = "h-14"

  [params.icon]
    #If you want to use FontAwesome, set this parameter to true.
    fontawesome = true

  [params.homepage_meta_tags]
    meta_description = "A Hugo Theme for OSSProject, Companies, Organization..."
    meta_og_title = "Tella"
    meta_og_type = "website"
    meta_og_url = "https://tella.pages.dev"
    meta_og_image = "https://raw.githubusercontent.com/opera7133/tella/master/images/tn.png"
    meta_og_description = "A Hugo Theme for OSSProject, Companies, Organization..."
    meta_twitter_card = "summary_large_image"
    meta_twitter_site = "@username"
    meta_twitter_creator = "@username"

[menu]

  [[menu.main]]
    identifier = "products"
    name = "Productos"
    url = "/products/"
    weight = 1

  [[menu.main]]
    identifier = "services"
    name = "Servicios"
    url = "/services/"
    weight = 2

  [[menu.main]]
    identifier = "contact"
    name = "Contactanos"
    url = "/contact/"
    weight = 3
